service: xbox-gamer-slack-posting

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: prod
  profile: Madushan
  versionFunctions: false

functions:
  slack_posting_webhook:
    handler: handler.slack_posting_webhook
    description: Function description goes here