service: xbox-gamer-slack-slash-commands

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: prod
  profile: Madushan
  versionFunctions: false

  environment:
    #xbox
    XBOX_PROFILE_ID: ${file(./secrets.env.yml):xbox.XBOX_PROFILE_ID}
    #xboxapi
    XBOX_API_BASE_URL: ${file(./secrets.env.yml):xboxapi.XBOX_API_BASE_URL}
    XBOX_API_KEY: ${file(./secrets.env.yml):xboxapi.XBOX_API_KEY}

functions:
  get_xboxgamer_info:
    handler: handler.get_xboxgamer_info
    description: Function description goes here