service: xbox-gamer-slack-slash-commands

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: prod
  profile: Madushan
  versionFunctions: false

  environment:
    #xbox
    XBOX_PROFILE_ID: ${file(./secrets.env.yml):xbox.XBOX_PROFILE_ID}
    #xboxapi
    XBOX_API_BASE_URL: ${file(./secrets.env.yml):xboxapi.XBOX_API_BASE_URL}
    XBOX_API_KEY: ${file(./secrets.env.yml):xboxapi.XBOX_API_KEY}
    # slack
    SLACK_TOKEN: ${file(./secrets.env.yml):slack.SLACK_TOKEN}

functions:
  get_xboxgamer_info:
    handler: handler.get_xboxgamer_info
    description: Function description goes here
    events:
      - http:
          method: POST
          path: slash-commands-post
    
    layers:
      # using publically distributed lambda layer found here --> https://github.com/keithrozario/Klayers/blob/master/deployments/python3.8/arns/us-east-2.json
      - "arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-requests:1" 